/*  clk_test.c - The simplest kernel module.
 */
#include <linux/kernel.h>
#include <linux/init.h>
#include <linux/module.h>
#include <linux/slab.h>
#include <linux/io.h>
#include <linux/interrupt.h>

#include <linux/of_address.h>
#include <linux/of_device.h>
#include <linux/of_platform.h>

#include <linux/list.h>

#include <linux/cdev.h>
#include <linux/proc_fs.h>
#include <asm/uaccess.h>
#include <asm/io.h>
#include <linux/time.h>

#include <linux/fs.h>
#include <linux/syscalls.h>

#include <asm/siginfo.h>
#include <linux/sched.h>
#include <linux/pid_namespace.h>
#include <linux/pid.h>

/* Standard module information, edit as appropriate */
MODULE_LICENSE("GPL");
MODULE_AUTHOR
    ("Xilinx Inc.");
MODULE_DESCRIPTION
    ("clk_wiz - loadable module template generated by petalinux-create -t modules");

#define DRIVER_NAME "clk_wiz"

/* Simple example of how to receive command line parameters to your module.
   Delete if you don't need them */
unsigned myint = 0xdeadbeef;
char *mystr = "default";

module_param(myint, int, S_IRUGO);
module_param(mystr, charp, S_IRUGO);

struct clk_wiz_local {
	int irq;
	unsigned long mem_start;
	unsigned long mem_end;
	void __iomem *base_addr;
};



/*global pointer*/
struct clk_wiz_local *gp;


static irqreturn_t clk_wiz_irq(int irq, void *lp)
{
	printk("clk_wiz interrupt\n");
	return IRQ_HANDLED;
}


/****************************************************/
/*****       file operations struct       *****/
/****************************************************/
int clk_wiz_open(struct inode *inode, struct file *file);
int clk_wiz_release(struct inode *inode, struct file *file);
int clk_wiz_ioctl(struct inode *inode, struct file *file, unsigned int cmd);

static struct file_operations irq_test_fops = {
	.owner = THIS_MODULE,
	.open = clk_wiz_open,
	.release  = clk_wiz_release,
	.read = NULL,
	.write  = NULL,
	.mmap = NULL,
	.unlocked_ioctl = clk_wiz_ioctl,
};

/****************************************************/
/*****        open & close & ioctl        *****/
/****************************************************/
#define STATUS_REG 0x04
#define CLK_OUT_0 0x208
#define CLK_OUT_1 0x214
#define CLK_CONFIG 0x200
#define CLK_LOAD 0x25c

int status;
int out0_div, out1_div;

int clk_wiz_open(struct inode *inode, struct file *file){

	printk("clk test open call\n");
	
	iowrite32(0x00000a0a, gp->base_addr + CLK_CONFIG);	/*set voc freq 100MHz*/
	iowrite32(0x00000003,gp->base_addr + CLK_OUT_0);		/*set clk_out_0 33MHz*/
	iowrite32(0x00000006,gp->base_addr + CLK_OUT_1);		/*set clk_out_1 16Mhz*/
	status = ioread32(gp->base_addr + STATUS_REG);
		if(!status){
			printk("clk config failed\n");
			return -1;
		}
	iowrite32(0x00000007, gp->base_addr + CLK_LOAD);		
	iowrite32(0x00000002, gp->base_addr + CLK_LOAD);	
	return 0;
}

int clk_wiz_release(struct inode *inode, struct file *file){
	
	printk("clk test close call\n");
	return 0;	

}
/****************************************************/
/*****    define reg address & ioctl cmd  *****/
/****************************************************/



int clk_wiz_ioctl(struct inode *inode, struct file *file, unsigned int cmd){

	//cmd is div value
	printk("div value : %d \n", cmd);
	out0_div = cmd;
	out1_div = cmd*2;

	iowrite32(out0_div,gp->base_addr + CLK_OUT_0);	
	iowrite32(out1_div,gp->base_addr + CLK_OUT_1);	
	status = ioread32(gp->base_addr + STATUS_REG);
		if(!status){
			printk("clk config failed\n");
			return -1;
		}
	iowrite32(0x00000007, gp->base_addr + CLK_LOAD);		
	iowrite32(0x00000002, gp->base_addr + CLK_LOAD);	
	printk("clk wiz ioctl called\n");
	return 0;

}


/****************************************************/
/*****             init & exit            *****/
/****************************************************/


#define MINOR_COUNT 2

static dev_t dev_id;
static struct cdev c_dev;

static int init_clk_wiz(void){
	int ret;
	
	ret = alloc_chrdev_region(&dev_id, 0, MINOR_COUNT, DRIVER_NAME);
	
	if(ret < 0){
		printk(KERN_WARNING, "alloc_chrdev_region failed\n");
		return ret;
	}

	cdev_init(&c_dev, &irq_test_fops);
	c_dev.owner = THIS_MODULE;


	ret = cdev_add(&c_dev, dev_id, MINOR_COUNT);
	printk("add cdev: major %d, minor %d.\n", MAJOR(dev_id), MINOR(dev_id));

	if(ret < 0){
		printk(KERN_WARNING, "cdev_add failed\n");
		return ret;
	}

	return 0;
	
}

static void exit_clk_wiz(void){
	cdev_del(&c_dev);
	unregister_chrdev_region(dev_id, MINOR_COUNT);
}

/****************************************************/
/*****       		probe		      *****/
/****************************************************/

static int clk_wiz_probe(struct platform_device *pdev)
{
	struct resource *r_irq; /* Interrupt resources */
	struct resource *r_mem; /* IO mem resources */
	struct device *dev = &pdev->dev;
	struct clk_wiz_local *lp = NULL;

	int rc = 0;
	
	dev_info(dev, "Device Tree Probing\n");

	/* Get iospace for the device */
	r_mem = platform_get_resource(pdev, IORESOURCE_MEM, 0);
	if (!r_mem) {
		dev_err(dev, "invalid address\n");
		return -ENODEV;
	}
	
	lp = (struct clk_wiz_local *) kmalloc(sizeof(struct clk_wiz_local), GFP_KERNEL);
	if (!lp) {
		dev_err(dev, "Cound not allocate clk_wiz device\n");
		return -ENOMEM;
	}
	
	dev_set_drvdata(dev, lp);
	
	lp->mem_start = r_mem->start;
	lp->mem_end = r_mem->end;

	if (!request_mem_region(lp->mem_start,
				lp->mem_end - lp->mem_start + 1,
				DRIVER_NAME)) {
		dev_err(dev, "Couldn't lock memory region at %p\n",
			(void *)lp->mem_start);
		rc = -EBUSY;
		goto error1;
	}

	lp->base_addr = ioremap(lp->mem_start, lp->mem_end - lp->mem_start + 1);
	if (!lp->base_addr) {
		dev_err(dev, "clk_wiz: Could not allocate iomem\n");
		rc = -EIO;
		goto error2;
	}

	/* Get IRQ for the device */
	r_irq = platform_get_resource(pdev, IORESOURCE_IRQ, 0);
	if (!r_irq) {
		dev_info(dev, "no IRQ found\n");
		dev_info(dev, "clk_wiz at 0x%08x mapped to 0x%08x\n",
			(unsigned int __force)lp->mem_start,
			(unsigned int __force)lp->base_addr);
		/*copy to global pointer*/
		gp = lp;
		return 0;
	}
	lp->irq = r_irq->start;
	
	rc = request_irq(lp->irq, &clk_wiz_irq, 0, DRIVER_NAME, lp);
	if (rc) {
		dev_err(dev, "testmodule: Could not allocate interrupt %d.\n",
			lp->irq);
		goto error3;
	}

	/*copy to global pointer*/
	gp = lp;
	
	dev_info(dev,"clk_wiz at 0x%08x mapped to 0x%08x, irq=%d\n",
		(unsigned int __force)lp->mem_start,
		(unsigned int __force)lp->base_addr,
		lp->irq);
	return 0;
error3:
	free_irq(lp->irq, lp);
error2:
	release_mem_region(lp->mem_start, lp->mem_end - lp->mem_start + 1);
error1:
	kfree(lp);
	dev_set_drvdata(dev, NULL);
	return rc;
}

static int clk_wiz_remove(struct platform_device *pdev)
{
	struct device *dev = &pdev->dev;
	struct clk_wiz_local *lp = dev_get_drvdata(dev);
	free_irq(lp->irq, lp);
	release_mem_region(lp->mem_start, lp->mem_end - lp->mem_start + 1);
	kfree(lp);
	dev_set_drvdata(dev, NULL);
	return 0;
}

#ifdef CONFIG_OF
static struct of_device_id clk_wiz_of_match[] = {
	{ .compatible = "xlnx,clocking-wizard", },
	{ /* end of list */ },
};
MODULE_DEVICE_TABLE(of, clk_wiz_of_match);
#else
# define clk_wiz_of_match
#endif


static struct platform_driver clk_wiz_driver = {
	.driver = {
		.name = DRIVER_NAME,
		.owner = THIS_MODULE,
		.of_match_table	= clk_wiz_of_match,
	},
	.probe		= clk_wiz_probe,
	.remove		= clk_wiz_remove,
};

static int __init clk_wiz_init(void)
{
	int ret;
	printk("<1>Hello module world.\n");
	printk("<1>Module parameters were (0x%08x) and \"%s\"\n", myint,
	       mystr);
	ret = platform_driver_register(&clk_wiz_driver);
	init_clk_wiz();
	return ret;
};

static void __exit clk_wiz_exit(void)
{
	exit_clk_wiz();
	platform_driver_unregister(&clk_wiz_driver);
	printk(KERN_ALERT "Goodbye module world.\n");
}

module_init(clk_wiz_init);
module_exit(clk_wiz_exit);

