# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg400-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Vivado_projects/Geyser_mem_ver1.1/Geyser_mem_ver1.1.cache/wt [current_project]
set_property parent.project_path C:/Vivado_projects/Geyser_mem_ver1.1/Geyser_mem_ver1.1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:microzed_7020:part0:1.1 [current_project]
set_property ip_repo_paths c:/Vivado_projects/source_code/Geyser_mem_01 [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_mem {
  C:/Vivado_projects/source_code/Geyser_mem_01/Init_bram/bram.dat
  C:/Vivado_projects/source_code/Geyser_mem_01/Init_bram/btst.dat
}
read_verilog -library xil_defaultlib {
  C:/Vivado_projects/source_code/Geyser_mem_01/uartlite.v
  C:/Vivado_projects/source_code/Geyser_mem_01/buscon16.v
}
synth_design -top BusController16 -part xc7z020clg400-1
write_checkpoint -noxdef BusController16.dcp
catch { report_utilization -file BusController16_utilization_synth.rpt -pb BusController16_utilization_synth.pb }
